### ISSUE TITLE
German Version of NicoAiko not merged right.

### ISSUE THREAD

**Issue by cptpiepmatz** [albertjan/hyper-yes#4]
I don't know what happened here but the fork of @NicoAiko wasn't merged successfully.
That's a bummer for me.

For your interest, you can easily add to your `.hyper.js` into the `plugins` section:
```
"hyper-yes#github:NicoAiko/hyper-yes"
```

This will install the fork of @NicoAiko.

**Comment by NicoAiko** [comment]
Did it work for you?

For me it didn't, so I stopped as I got a new device that doesn't run Windows ^^

**Comment by cptpiepmatz** [comment]
It will install your fork but it doesn't work at all

sadly...

**Comment by NicoAiko** [comment]
Yeah, unfortunately.

I thought I just had to implement a different language string there for it to work, but Hyper / Powershell doesn't think so...

**Comment by cptpiepmatz** [comment]
I give it a shot, maybe i can fix it up

**Comment by cptpiepmatz** [comment]
I currently don't have the ability to compare my results with an english running machine, so i close it for now
