### ISSUE TITLE
Doesn't appear to be working

### ISSUE THREAD

**Issue by fcFn** [albertjan/hyper-yes#7]
Nothing changed after installing the plugin and restarting Hyper (I removed all the other plugins I had just in case and tried the test script that is in the GIF in the README.md). Could it be that it no longer works given the last update was 2 years ago?

**Comment by albertjan** [comment]
I haven't used hyper or this extension for ages. I'm not surprised it's broken. soz

**Comment by fcFn** [comment]
@albertjan Did you find some alternative solution to the problem with the prompt (regardless of Hyper), perhaps?

**Comment by albertjan** [comment]
Nah, I'm on Mac now.
